### ISSUE TITLE
All Terms are deselected after dragging a term from YES box to NO box

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/HpoTextMining#12]
Hi @kingmanzhang, the dragging of terms from YES to NO box works now. However, if you select some terms and then drag another term from YES into NO box, then all the terms are deselected. Do you thing that this could be fixed?

[A demonstration video](https://github.com/monarch-initiative/HpoTextMining/files/2702126/TermsAreDeselectedAfterDrag.zip)

**Comment by kingmanzhang** [comment]
I realized why it happens (because the change listener will recreate checkboxes after removing a term). I will try to fix it soon.
