### ISSUE TITLE
Upgrade to phenol

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoTextMining#3]
Can we plan to upgrade to phenol?
https://github.com/monarch-initiative/phenol
this would simplify application code that is using this widget, since we are switching the HPO Parsing and analysis to phenol. This could be done in a separate branch until phenol goes onto maven central.
https://github.com/monarch-initiative/phenol

**Comment by kingmanzhang** [comment]
90% completed. Some display errors to be fixed.

**Comment by pnrobinson** [comment]
issue is completed, I think.
