### ISSUE TITLE
phenol version

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoTextMining#6]
There are a few inconsistencies with the latest phenol version, 1.3.1-SNAPSHOT in the master branch of HpoTextMining. I think it might be best to wait until we have merged develop and master again to work on this so as not to introduce inconsistencies. Jules has just made a few changes to simplify the API and make things more efficient, and so we want to use the latest version here. Also, I think I still saw some Ontologizer code, and we should replace that with the corresponding phenol classes. Can we discuss a plan of attack?

**Comment by ielis** [comment]
I think that after approving changes present at #7 pull request we are good to go for the latest stable phenol version. We might even do that within the pull request so that the latest phenol version would be part of the upcoming hpotextmining 0.2.3 release.
